Jonnitto:
  PrettyEmbedVideo:
    defaults:
      # Should the video be opened on a lightbox? Per default this is set via the node properties
      lightbox: false

      # If true, the video automatically begins to play back as soon
      # as it can do so without stopping to finish loading the data.
      autoplay: false

      # If true, the browser will offer controls to allow the user to control
      # video playback, including volume, seeking, and pause/resume playback.
      controls: true

      # If true, the browser will automatically seek back
      # to the start upon reaching the end of the video.
      loop: false

      # Whether the video is muted upon loading. Set automatically to true if autoplay is enabled
      muted: false

      # This enumerated attribute is intended to provide a hint to the browser about what
      # the author thinks will lead to the best user experience with regards to what content
      # is loaded before the video is played. It may have one of the following values:
      #  - none       Indicates that the video should not be preloaded.
      #  - metadata   Indicates that only video metadata (e.g. length) is fetched.
      #  - auto       Indicates that the whole video file can be downloaded, even if the user is not expected to use it
      preload: none

      # Whether the video plays inline on supported mobile devices.
      # Note that if set to false it does not imply that the video will always be played in fullscreen.
      playsinline: true

      # https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-crossorigin
      # anonymous || use-credentials || true || false
      crossorigin: false
